// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ7CJb1oMgsf_Untfnz3vtbN8oyPJCwuU',
    appId: '1:412999233049:web:bfe69ce26fe0d48e5a8488',
    messagingSenderId: '412999233049',
    projectId: 'agrivi-93678',
    authDomain: 'agrivi-93678.firebaseapp.com',
    storageBucket: 'agrivi-93678.appspot.com',
    measurementId: 'G-FK2CP4LZ43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJQhrpKjmuE2X8DbJS3HeNC-3wlcOXJI0',
    appId: '1:412999233049:android:b52f06c6070fe82d5a8488',
    messagingSenderId: '412999233049',
    projectId: 'agrivi-93678',
    storageBucket: 'agrivi-93678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACNsq25gprSsEn-tsMzThssH2aFcIjF2Q',
    appId: '1:412999233049:ios:85ea63104cda5f0c5a8488',
    messagingSenderId: '412999233049',
    projectId: 'agrivi-93678',
    storageBucket: 'agrivi-93678.appspot.com',
    iosBundleId: 'com.example.tStore',
  );
}
